#!/usr/bin/env bash
# Start the Automatic1111-compatible proxy that LibreChat's stable-diffusion
# tool calls. Images are generated by a local Ollama image model on this Mac.
#
# Usage:
#   npm run start:image-gen
#   OLLAMA_IMAGE_MODEL=x/flux2-klein:4b npm run start:image-gen
#
# Does not interrupt an in-progress `ollama pull`. If the image model is not
# present yet, pull it after the other download finishes:
#   ollama pull x/flux2-klein:4b

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OLLAMA_URL="${OLLAMA_URL:-http://127.0.0.1:11434}"
OLLAMA_IMAGE_MODEL="${OLLAMA_IMAGE_MODEL:-x/flux2-klein:4b}"
SD_PROXY_PORT="${SD_PROXY_PORT:-7860}"
PROXY_PID_FILE="${TMPDIR:-/tmp}/rakaai-ollama-sd-proxy.pid"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1"
    exit 1
  fi
}

require_cmd node
require_cmd ollama
require_cmd curl

ollama_ready() {
  curl -sf "$OLLAMA_URL/api/tags" >/dev/null 2>&1
}

pull_in_progress() {
  pgrep -f 'ollama pull' >/dev/null 2>&1
}

model_present() {
  ollama list 2>/dev/null | awk 'NR > 1 { print $1 }' | grep -qx "$OLLAMA_IMAGE_MODEL"
}

if ! ollama_ready; then
  echo "Ollama is not running at $OLLAMA_URL. Start it first: brew services start ollama"
  exit 1
fi

if ! model_present; then
  if pull_in_progress; then
    echo "An Ollama pull is already running. Not starting another download."
    echo "When it finishes, run: ollama pull $OLLAMA_IMAGE_MODEL"
    echo "Then re-run: npm run start:image-gen"
    exit 1
  fi
  echo "Pulling $OLLAMA_IMAGE_MODEL (~5.7 GB, fits 16 GB Apple Silicon)..."
  ollama pull "$OLLAMA_IMAGE_MODEL"
fi

if curl -sf "http://127.0.0.1:${SD_PROXY_PORT}/health" >/dev/null 2>&1; then
  echo "Image-gen proxy is already running on port $SD_PROXY_PORT"
  exit 0
fi

echo "Starting image-gen proxy on port $SD_PROXY_PORT (model $OLLAMA_IMAGE_MODEL)..."
nohup env OLLAMA_URL="$OLLAMA_URL" OLLAMA_IMAGE_MODEL="$OLLAMA_IMAGE_MODEL" SD_PROXY_PORT="$SD_PROXY_PORT" \
  node "$ROOT_DIR/scripts/ollama-sd-proxy.js" >/tmp/rakaai-ollama-sd-proxy.log 2>&1 &
echo $! >"$PROXY_PID_FILE"

for _ in $(seq 1 20); do
  if curl -sf "http://127.0.0.1:${SD_PROXY_PORT}/health" >/dev/null 2>&1; then
    echo "Image-gen proxy is ready at http://127.0.0.1:${SD_PROXY_PORT}"
    echo "LibreChat Agents → add the Stable Diffusion tool → ask it to generate an image."
    exit 0
  fi
  sleep 0.25
done

echo "Proxy started but /health is not ready yet. Check /tmp/rakaai-ollama-sd-proxy.log"
exit 1
