#!/usr/bin/env bash
# Start the Automatic1111-compatible proxy that LibreChat's stable-diffusion
# tool calls. Images are generated by local MLX mflux (Flux.2 Klein 4B).
#
# Usage:
#   npm run start:image-gen
#   MFLUX_MODEL=flux2-klein-4b npm run start:image-gen

set -euo pipefail

export PATH="${HOME}/.local/bin:/opt/homebrew/bin:${PATH}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MFLUX_BIN="${MFLUX_BIN:-mflux-generate-flux2}"
MFLUX_MODEL="${MFLUX_MODEL:-flux2-klein-4b}"
SD_PROXY_PORT="${SD_PROXY_PORT:-7860}"
PROXY_PID_FILE="${TMPDIR:-/tmp}/rakaai-ollama-sd-proxy.pid"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1"
    exit 1
  fi
}

require_cmd node
require_cmd curl
require_cmd "$MFLUX_BIN"

if curl -sf "http://127.0.0.1:${SD_PROXY_PORT}/health" >/dev/null 2>&1; then
  echo "Image-gen proxy is already running on port $SD_PROXY_PORT"
  exit 0
fi

echo "Starting image-gen proxy on port $SD_PROXY_PORT (mflux $MFLUX_MODEL)..."
nohup env PATH="$PATH" MFLUX_BIN="$MFLUX_BIN" MFLUX_MODEL="$MFLUX_MODEL" SD_PROXY_PORT="$SD_PROXY_PORT" \
  node "$ROOT_DIR/scripts/ollama-sd-proxy.js" >/tmp/rakaai-ollama-sd-proxy.log 2>&1 &
echo $! >"$PROXY_PID_FILE"

for _ in $(seq 1 20); do
  if curl -sf "http://127.0.0.1:${SD_PROXY_PORT}/health" >/dev/null 2>&1; then
    echo "Image-gen proxy is ready at http://127.0.0.1:${SD_PROXY_PORT}"
    echo "LibreChat Agents → add the Stable Diffusion tool → ask it to generate an image."
    exit 0
  fi
  sleep 0.25
done

echo "Proxy started but /health is not ready yet. Check /tmp/rakaai-ollama-sd-proxy.log"
exit 1
